[project]

name = "spq"
version = "0.1.0"
description = "spq - simple physical quantities"
dependencies = [
  "numpy"
]


[tool.setuptools.packages.find]
# All the following settings are optional:
where = ["."]  # ["."] by default
include = ["spq"]  # ["*"] by default